### ISSUE TITLE
Getting the list of all followers results in JsonSerializationException

### ISSUE THREAD

**Issue by an40us** [TwitchLib/TwitchLib#381]
Running this line of code:

`var AllFollows = await api.Channels.v5.GetChannelFollowersAsync(ChannelID);`

results in this exception:
**"Could not create an instance of type TwitchLib.Api.Interfaces.IFollow. Type is an interface or abstract class and cannot be instantiated. Path 'follows[0].created_at', line 1, position 71."**

Getting the list of subscribers, on the other hand, works without any issues.
TwitchLib version 2.0.1, Newtonsoft.Json version 11.0.1

**Comment by swiftyspiffy** [comment]
Will look into this in like 10 hours.

**Comment by Mahsaap** [comment]
@swiftyspiffy ^ did you get a chance to look at that? I think we did determine it was a merge thing?

**Comment by swiftyspiffy** [comment]
@an40us should be fixed with the recent commits.

**Comment by an40us** [comment]
@swiftyspiffy Still no luck, getting the same exception on the same conditions. Are those commits in master branch?

**Comment by swiftyspiffy** [comment]
Will check on this again.

**Comment by swiftyspiffy** [comment]
@an40us want to give it a go now?

**Comment by an40us** [comment]
No exceptions anymore, works perfectly. Thank you, @swiftyspiffy .

**Comment by swiftyspiffy** [comment]
Great!
